#!/bin/bash

BLACK="\033[0;37m"
GREEN="\033[1;32m"
RED="\033[0;31m"
NOCOLOR="\033[0m"

printf "${BLACK}========== 🟠 Run Commit 🟠 ==========\n${NOCOLOR}"

COMMIT_FILE=$1

COMMIT_TYPES=(
  "🤖 Chore    : (자잘한 수정)     "
  "📚 Docs     : (문서 관련)     "
  "✨  Feat     : (기능 추가)     "
  "🐛 Fix      : (버그 수정)     "
  "⚡  Perf     : (성능 개선)     "
  "🔨 Refactor : (리팩토링)     "
  "🚨 Test     : (테스트)     "
)

exec < /dev/tty
PS3="Select Commit Type: "
while [ "$COMMIT_TYPE" = "" ]
do
  select COMMIT_TYPE in "${COMMIT_TYPES[@]}"
  do
    break
  done

  if [ "$COMMIT_TYPE" = "" ]
  then
    printf "${RED}Invalid Commit Type\n${NOCOLOR}"
  fi
done

while [ "$COMMIT_MESSAGE" = "" ]
do
  read -p "Input Commit Message: " COMMIT_MESSAGE

  if [ "$COMMIT_MESSAGE" = "" ]
  then
    printf "${RED}Required Commit Message\n${NOCOLOR}"
    continue
  fi

  echo $(echo $COMMIT_TYPE | sed "s| :|:|g" | sed "s|(.*)|$COMMIT_MESSAGE|g") > $COMMIT_FILE
  printf "${GREEN}"
  break
done
