# Generated by Django 3.2.9 on 2022-02-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('code', models.CharField(max_length=6, verbose_name='인증번호')),
                ('token', models.CharField(max_length=40, verbose_name='토큰')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('phone', models.CharField(max_length=11, verbose_name='휴대폰번호')),
                ('code', models.CharField(max_length=6, verbose_name='인증번호')),
                ('token', models.CharField(max_length=40, verbose_name='토큰')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
