# Generated by Django 3.2.9 on 2022-02-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmTalkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('to', models.CharField(max_length=11, verbose_name='수신자')),
                ('template_code', models.CharField(max_length=16, verbose_name='템플릿 코드')),
                ('body', models.TextField(verbose_name='내용')),
                ('status', models.CharField(blank=True, choices=[('S', '성공'), ('F', '실패')], editable=False, max_length=1, null=True, verbose_name='상태')),
                ('fail_reason', models.TextField(blank=True, null=True, verbose_name='실패사유')),
            ],
            options={
                'verbose_name': '알림톡 로그',
                'verbose_name_plural': '알림톡 로그',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('to', models.EmailField(max_length=254, verbose_name='수신자')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('status', models.CharField(blank=True, choices=[('S', '성공'), ('F', '실패')], editable=False, max_length=1, null=True, verbose_name='상태')),
            ],
            options={
                'verbose_name': '이메일 로그',
                'verbose_name_plural': '이메일 로그',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PhoneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('to', models.CharField(max_length=11, verbose_name='수신자')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('status', models.CharField(blank=True, choices=[('S', '성공'), ('F', '실패')], editable=False, max_length=1, null=True, verbose_name='상태')),
                ('fail_reason', models.TextField(blank=True, null=True, verbose_name='실패사유')),
            ],
            options={
                'verbose_name': '휴대폰 로그',
                'verbose_name_plural': '휴대폰 로그',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('status', models.CharField(blank=True, choices=[('S', '성공'), ('F', '실패')], editable=False, max_length=1, null=True, verbose_name='상태')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음')),
            ],
            options={
                'verbose_name': '푸시 로그',
                'verbose_name_plural': '푸시 로그',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='제목')),
                ('body', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('status', models.TextField(choices=[('S', '성공'), ('F', '실패')], max_length=1, verbose_name='상태')),
            ],
            options={
                'verbose_name': '테스크 로그',
                'verbose_name_plural': '테스크 로그',
                'ordering': ['-created'],
            },
        ),
    ]
