# Generated by Django 3.2.9 on 2022-02-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('uid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='UID')),
                ('token', models.CharField(max_length=256, verbose_name='값')),
            ],
            options={
                'verbose_name': '디바이스',
                'verbose_name_plural': '디바이스',
            },
        ),
    ]
